apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qj121uzq1-python-gitops
  description: This is GitOps manifest for qj121uzq1-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qj121uzq1-python
    backstage.io/kubernetes-id: qj121uzq1-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qj121uzq1-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qj121uzq1-python
